### ISSUE TITLE
Add support for Bootstrap

### ISSUE THREAD

**Issue by acolson** [GasStationTV/angular-coding-exercise#17] opened 2015-05-16 04:03 UTC
We should allow candidates to switch between Foundation for Apps and Bootstrap for styling. However, this may complicate the structure of the Welcome directive.

**Comment by davezuko** [comment] 2015-06-04 14:22
Should we default to Bootstrap since candidates are more likely to be familiar with it? The Foundation for Apps documentation is pretty tragic, so I'm not sure if using it as a default is the best idea.

**Comment by Aourin** [comment] 2015-06-04 14:34
It is true that it is kind of the one that most people know, but is that such a bad thing to throw something new at them? Granted there is a lot of stuff packed into it, the repo was intended to be a provides all the annoying setup stuff so they can get to coding. Maybe looking into the docs and figuring out how to use foundation might be beneficial. This is honestly more to play devil's advocate and not because I "want" foundation in.

**Comment by Aourin** [comment] 2015-06-04 14:35
That being said, foundation for apps has proven to be odd when creating some of its layout components.

**Comment by davezuko** [comment] 2015-06-04 14:39
True, I'm just wondering how much it will stump a junior developer who may not have much, if any, experience with sass; may never have used flexbox; and is thrown into an app that - while well documented and not overly complicated - may have a large shock value for someone newer to the industry.

Just think about everything that's going on: Angular, NPM, Webpack, Sass/Jade + their imports into a js file, ES6, Karma, Mocha, Chai, Foundation. Though again, to your point, it is to see how resourceful they can be on their own, so it is a valid argument.

**Comment by davezuko** [comment] 2015-06-05 00:08
I just wired up Webpack to load Bootstrap in correctly, see [feature/bootstrap](https://github.com/GasStationTV/angular-coding-exercise/tree/feature/bootstrap). Need someone to update the templates/docs accordingly, however.

**Comment by davezuko** [comment] 2015-06-05 01:42
Closing since the above branch has now been merged into master.

**Closed by davezuko** 2015-06-05 01:42 UTC
Labels: enhancement
